name: Build image and deploy to production environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Generate image tag
        id: meta
        run: |
          echo "tag=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.APP_NAME }}:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.APP_NAME }}:${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP_PROD }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY_PROD }}
          port: 22
          script: |
            set -eou pipefail

            mkdir -p ${{ secrets.APP_PATH }}

            cd ${{ secrets.APP_PATH }}
            if [ -d .git ]; then
              git pull origin main
            else
              git clone -b main ${{ secrets.REPO_URL }} .
            fi

            cat > .env << 'EOF'
            ${{ secrets.DOTENV_FILE_PROD }}
            EOF

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

            docker compose -f compose.prod.yaml down --remove-orphans || true

            docker compose -f compose.prod.yaml pull
            docker compose -f compose.prod.yaml up -d --remove-orphans

            sleep 5

            docker compose -f compose.preview.yaml ps

            docker system prune -f
